### ISSUE TITLE
Pretrained model?

### ISSUE THREAD

**Issue by Fred-Erik** [wangchx67/FourLLIE#1]
Are you planning to release a trained model? I'm interested to see how this model compares in terms of image quality and inference speed.

**Comment by Fred-Erik** [comment]
It would be most appreciated!

On a related note, that dataset link you provided for the LSRW dataset needs a Baidu account, which I cannot easily create as someone who doesn't live in China. The LOL-real and LOL-sys links provided only contain a few results, not training or validation data. If you can also upload those datasets to website that doesn't require an account to download like Google Drive, Wetransfer or Dropbox, that would be very helpful!

**Comment by wangchx67** [comment]
You can provide an email address and I directly send to you.

--------------原始邮件--------------
发件人："Fred-Erik ***@***.***&gt;;
发送时间：2023年8月15日(星期二) 晚上7:49
收件人："wangchx67/FourLLIE" ***@***.***&gt;;
抄送："王晨曦 ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [wangchx67/FourLLIE] Pretrained model? (Issue #1)
-----------------------------------

 

 
It would be most appreciated!
 
On a related note, that dataset link you provided for the LSRW dataset needs a Baidu account, which I cannot easily create as someone who doesn't live in China. The LOL-real and LOL-sys links provided only contain a few results, not training or validation data. If you can also upload those datasets to website that doesn't require an account to download like Google Drive, Wetransfer or Dropbox, that would be very helpful!

**Comment by Fred-Erik** [comment]
Thank you for the pretrained models you sent! I've tried a few of them on my dataset but I think I might have a denoising problem instead of a low-light image enhancement problem.

Inputs:

![input](https://github.com/wangchx67/FourLLIE/assets/2436555/8b48c39c-1227-43cf-bd41-6ae359e75d55)
![input2](https://github.com/wangchx67/FourLLIE/assets/2436555/afde7ee9-0b6f-4682-8ef8-1396ba4c2152)

Simple auto leveling results:

![simple](https://github.com/wangchx67/FourLLIE/assets/2436555/083e79aa-077c-4ea8-921d-8d67df5f3ab9)
![simple2](https://github.com/wangchx67/FourLLIE/assets/2436555/1fd84ea3-0d40-42e8-afbf-9ff81dd2d5c6)

Result with your model:

![result](https://github.com/wangchx67/FourLLIE/assets/2436555/032e785b-c3a4-4de2-8e9e-6e4ac059eb96)
![result2](https://github.com/wangchx67/FourLLIE/assets/2436555/9544c738-834d-424c-97cb-2a46cebefbf8)

It doesn't improve much compared to simply using auto levels. And the result still looks bad, but it seems to mainly be due to the very present noise.

**Comment by wangchx67** [comment]
Actually, the noise distribution of real scence
is very different with that of existing LLIE datasets (e.g., LSRW and LOL). Maybe you can try to train the model in SID, or you can calibirate the noise distribution of your own dataset with the camera settings and re-train the model.
--------------原始邮件--------------
发件人："Fred-Erik ***@***.***&gt;;
发送时间：2023年8月15日(星期二) 晚上10:43
收件人："wangchx67/FourLLIE" ***@***.***&gt;;
抄送："王晨曦 ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [wangchx67/FourLLIE] Pretrained model? (Issue #1)
-----------------------------------

 

 
Thank you for the pretrained models you sent! I've tried a few of them on my dataset but I think I might have a denoising problem instead of a low-light image enhancement problem.
 
Inputs:
 

 
 
Simple auto leveling results:
 

 
 
Result with your model:
 

 
 
It doesn't improve much compared to simply using auto levels. And the result still looks bad, but it seems to mainly be due to the very present noise.

**Comment by GaoTianWL** [comment]
您好，可以麻烦您提供一下预训练模型吗820072494@qq.com
